name: smart pipeline
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: install eslint
        run: |
          npm install eslint --save-dev
          npm install --save-dev @eslint/js


      - name: install dependencies
        run: npm ci

      - name: run lint
        run: npm run lint